import { observable } from "mobx"

export class DataStore {

	@observable friends = [
		{
			id : 1001,
			first_name : 'Chuck',
			last_name : 'Norris',
			slug : 'chuck-norris',
			created_at : '2017-06-16 10:29:38',
			image : '/img/avatars/chuck-norris.jpg',
			email : 'user1@example.com',
			password : 'user1',
			email_verified : true,
			active : true,
			roles : ['Editor', 'Admin'],
		},
		{
			id : 1002,
			first_name : 'Black',
			last_name : 'Panther',
			slug : 'black-panther',
			created_at : '2017-06-16 10:29:38',
			image : '/img/avatars/black-panther.jpg',
			email : 'user2@example.com',
			password : 'user2',
			email_verified : true,
			active : true,
			roles : ['Editor'],
		},
		{
			id : 1003,
			first_name : 'Bat',
			last_name : 'Man',
			slug : 'bat-man',
			created_at : '2017-06-16 10:29:38',
			image : '/img/avatars/bat-man.jpg',
			email : 'user3@example.com',
			password : 'user3',
			email_verified : true,
			active : true,
			roles : ['Editor'],
		},
		{
			id : 1004,
			first_name : 'Neo',
			last_name : 'Neo',
			slug : 'neo-neo',
			created_at : '2017-06-16 10:29:38',
			image : '/img/avatars/neo-neo.jpg',
			email : 'user4@example.com',
			password : 'user4',
			email_verified : false,
			active : true,
			roles : [],
		},
		{
			id : 1005,
			first_name : 'Iron',
			last_name : 'Man',
			slug : 'iron-man',
			created_at : '2017-06-16 10:29:38',
			image : '/img/avatars/iron-man.jpg',
			email : 'user5@example.com',
			password : 'user5',
			email_verified : true,
			active : false,
			roles : [],
		},
	]

	@observable posts = [
		{
			id : 1001,
			user_id : 1001,
			author : 'David Alba',
			title : 'Lorem ipsum dolor sit amet 1',
			slug : 'clip-1',
			description : 'Lorem ipsum dolor sit amet 1',
			body : '<div><h2>Lorem ipsum dolor sit amet.</h2><br></br><p><b>Lorem ipsum</b> dolor sit amet, consectetuer adipiscing elit, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. </p></div>',
			url : 'example.com', 
			source : 'example.com', 
			date : '2017-05-10', 
			time : '08:05', 
			image : 'http://lorempixel.com/400/250', 
			active : false,
			created_at : '2017-06-16 10:29:38',
			tagged : [
				{ value : 'Kenya', label : 'Kenya' },
				{ value : 'Demo', label : 'Demo' },
				{ value : 'Private', label : 'Private' },
			],
		},
		{
			id : 1002,
			user_id : 1002,
			author : 'David Alba',
			title : 'Lorem ipsum dolor sit amet 2',
			slug : 'clip-2',
			description : 'Lorem ipsum dolor sit amet 2',
			body : '<div><h2>Lorem ipsum dolor sit amet.</h2><br></br><p><b>Lorem ipsum</b> dolor sit amet, consectetuer adipiscing elit, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. </p></div>',
			url : 'example.com', 
			source : 'example.com', 
			date : '2017-05-10', 
			time : '08:05', 
			image : 'http://lorempixel.com/400/250', 
			active : false,
			created_at : '2017-06-16 10:29:38',
			tagged : [
				{ value : 'Other', label : 'Other' },
			],
		},
		{
			id : 1003,
			user_id : 1003,
			author : 'Ellen DeGeneres',
			title : 'Tweet from Ellen DeGeneres',
			slug : 'clip-3',
			description : 'Tweet from Ellen DeGeneres',
			body : `<div>If only Bradley's arm was longer. Best photo ever. <a href="https://mobile.twitter.com/hashtag/oscars?src=hash" data-query-source="hashtag_click" class="twitter-hashtag dir-ltr" dir="ltr">#oscars</a><a href="http://t.co/C9U5NOtGap" data-pre-embedded="true" rel="nofollow" data-entity-id="440322224092745728" dir="ltr" data-url="https://twitter.com/TheEllenShow/status/440322224407314432/photo/1" data-tco-id="C9U5NOtGap" class="twitter_external_link dir-ltr tco-link has-expanded-path" target="_top" data-expanded-path="/TheEllenShow/status/440322224407314432/photo/1">pic.twitter.com/C9U5NOtGap</a></div>`,
			url : 'https://twitter.com/theellenshow/status/440322224407314432', 
			source : 'twitter.com', 
			date : '2017-05-10', 
			time : '08:05', 
			image : 'http://lorempixel.com/400/250', 
			active : false,
			created_at : '2017-06-16 10:29:38',
			tagged : [
				{ value : 'Kenya', label : 'Kenya' },
			],
		},
		{
			id : 1004,
			user_id : 1004,
			author : 'Xero Accounting Software',
			title : 'Welcome to Xero accounting software',
			slug : 'clip-4',
			description : 'Welcome to Xero accounting software',
			body : `<div>Xero accounting software is designed to revolutionise the way small businesses manage their finances. If doing the books is a nightmare for your small business, let this video show you how online accounting software can make your finances simple -- and even fun. Treehouse architect Arthur Wei explains how Xero's beautiful accounting software has made doing business a pleasure.\r\n\r\nXero is beautiful accounting software for small businesses and their advisors. See your cashflow in real-time with online accounting, invoicing, payroll, billing &amp; banking. Just login and see the difference. Sign up for a free trial at <a class="yt-simple-endpoint style-scope yt-formatted-string" href="/redirect?event=video_description&amp;q=https%3A%2F%2Fwww.xero.com%2Fsignup&amp;redir_token=Yxio6vMqzuBb7dzSd0RLDsr50d58MTUwNjQ1NjY3MUAxNTA2MzcwMjcx">https://www.xero.com/signup</a>\r\n\r\nLike us on Facebook: <a class="yt-simple-endpoint style-scope yt-formatted-string" href="/redirect?event=video_description&amp;q=http%3A%2F%2Fwww.facebook.com%2Fxero.accounting%2F&amp;redir_token=Yxio6vMqzuBb7dzSd0RLDsr50d58MTUwNjQ1NjY3MUAxNTA2MzcwMjcx">http://www.facebook.com/xero.accounting/</a>\r\nFollow us on Instagram: <a class="yt-simple-endpoint style-scope yt-formatted-string" href="/redirect?event=video_description&amp;q=https%3A%2F%2Fwww.instagram.com%2Fxero%2F&amp;redir_token=Yxio6vMqzuBb7dzSd0RLDsr50d58MTUwNjQ1NjY3MUAxNTA2MzcwMjcx">https://www.instagram.com/xero/</a>\r\nFollow us on Twitter: <a class="yt-simple-endpoint style-scope yt-formatted-string" href="/redirect?event=video_description&amp;q=http%3A%2F%2Fwww.twitter.com%2Fxero&amp;redir_token=Yxio6vMqzuBb7dzSd0RLDsr50d58MTUwNjQ1NjY3MUAxNTA2MzcwMjcx">http://www.twitter.com/xero</a>\r\nFollow us on LinkedIn: <a class="yt-simple-endpoint style-scope yt-formatted-string" href="/redirect?event=video_description&amp;q=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fxero&amp;redir_token=Yxio6vMqzuBb7dzSd0RLDsr50d58MTUwNjQ1NjY3MUAxNTA2MzcwMjcx">http://www.linkedin.com/company/xero</a>\r\nSubscribe to our Youtube Channel here: <a class="yt-simple-endpoint style-scope yt-formatted-string" href="https://www.youtube.com/user/XeroOnlineAccounting">https://www.youtube.com/user/XeroOnli...</a></div>`,
			url : 'https://www.youtube.com/watch?v=X-88wS75EeI', 
			source : 'youtube.com', 
			date : '2017-05-10', 
			time : '08:05', 
			image : 'http://lorempixel.com/400/250', 
			active : false,
			created_at : '2017-06-16 10:29:38',
			tagged : [
				{ value : 'Demo', label : 'Demo' },
				{ value : 'Other', label : 'Other' },
			],
		},
		{
			id : 1005,
			user_id : 1005,
			author : 'buzzfeedfood',
			title : 'Instagram by @buzzfeedfood',
			slug : 'clip-5',
			description : 'Instagram by @buzzfeedfood',
			body : `<div>23.5k Likes, 106 Comments - BuzzFeed Food (@buzzfeedfood) on Instagram: “Six slices for when you can't decide because, let's be real, that's all of us. Matcha red bean pie,…”</div>`,
			url : 'https://www.instagram.com/p/BZpWjnUB8Ei', 
			source : 'instagram.com', 
			date : '2017-05-10', 
			time : '08:05', 
			image : 'https://scontent-dft4-2.cdninstagram.com/t51.2885-15/e35/p1080x1080/22069289_277686046069449_4225676893556310016_n.jpg', 
			active : false,
			created_at : '2017-06-16 10:29:38',
			tagged : [
				{ value : 'Kenya', label : 'Kenya' },
			],
		},
	]

	@observable comments = []

}
let database = window.database = new DataStore

export default database
